name: law
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  restart_app: ^1.2.1
  file_picker: ^6.1.1
  cached_network_image: ^3.3.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  docx_template: ^0.3.6
  lottie: ^2.7.0
  animate_do: ^3.1.2
  open_file: ^3.3.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  pdf: ^3.10.6
  number_to_word_arabic: ^0.0.8
  awesome_dialog: ^3.1.0
  quickalert: ^1.0.2
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.3
  searchbar_animation: ^0.0.4
  anim_search_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
    - image/template.docx
