name: credit_card
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.1
  sliding_clipped_nav_bar: ^3.1.0+4
  font_awesome_flutter: ^10.5.0
  flutter_credit_card: ^3.0.7
  animate_do: ^3.0.2
  lottie: ^2.6.0
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  local_auth: ^2.1.7
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/