name: coldencastle
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.1.0
  animated_splash_screen: ^1.3.0
  animate_do: ^3.0.2
  flutter_zoom_drawer: ^3.0.4+1
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.0.2
  http: ^0.13.6
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0
  loading_indicator: ^3.1.0
  animated_bottom_navigation_bar: ^1.2.0
  geolocator: ^9.0.2
  intl: ^0.18.1
  clipboard: ^0.1.3
  signature: ^5.3.2
  image_picker: ^0.8.7+5
  xml: ^6.2.2
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:

  uses-material-design: true

  assets:
    - asset/