name: gcc
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.0
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  http: ^1.1.0
  xml: ^6.3.0
  animate_do: ^3.0.2
  lottie: ^2.6.0
  image_picker: ^1.0.2
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
