// ignore_for_file: file_names

import 'package:get/route_manager.dart';

class MyTransition extends Translations {
//  اللغات
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اسم المستخدم",
          "2": "كلمة المرور",
          "3": "نسيت كلمة السر",
          "4": "غرفة تجارة بغداد",
          "5": "اخبار الغرفة",
          "6": "دليل التاجر",
          "7": "مؤتمرات",
          "8": "معارض",
          "9": "الخدمات",
          "10": "مرحبا",
          "11": "بيانات التاجر",
          "12": "هوية التاجر",
          "13": "شهادة التاجر",
          "14": "شهادة المنشآ",
          "15": "الكتب الصادرة",
          "16": "الأعدادات",
          "17": "دليل التاجر",
          "18": "الملف الشخصي",
          "19": "اتصل بنا",
          "20": "اللغة",
          "21": "تسجيل الخروج",
          "22": "العربية",
          "23": "الأنكليزية",
          "24": "المتجر",
          "25": "الضرائب",
          "26": "الكمارك",
          "27": "خطآ",
          "28": "دخول التاجر",
          "29": "دخول الجهة الحكومية",
          "30": "تخطي",
          "31": "لديك حساب بالفعل",
          "32": "تهدي غرفة تجارة بغداد هذه الشهادة الى",
          "33": "صاحب",
          "34": "المنتسب لغرفة بغداد بتأريخ",
          "35": "عضو في الصنف ال",
          "36": "متمنين لكم النجاح في خدمة الأقتصاد العراقي",
          "37": "الأسم",
          "38": "الأسم التجاري",
          "39": "النشاط",
          "40": "الصنف",
          "41": "رقم الصنف",
          "42": "تاريخ الأنتساب",
          "43": "تاريخ النفاذ",
          "44": "المدير المفوض",
          "45": "الموقع",
          "46": "العنوان",
          "47": "رقم الهاتف",
          "48": "الموقع الألكتروني",
          "49": "حفظ",
          "50": "البحث",
          "51": "الرجاء الأختيار",
          "52": "يرجى التحقق من اتصال الأنترنت",
          "53": "يرجى التآكد من صحة المعلومات",
          "54": "ضريبة الدخل",
          "55": "ضريبة الشركات",
          "56": "منفيس",
          "57": "فواتير الاستيراد",
          "58": "التصريحات الكمركية",
          "59": "رسوم الكمارك",
          "60": "المعاملات الألكترونية",
          "61": "طلب معاملة",
          "62": "تتبع المعاملة",
          "63": "تسجيل الدخول",
          "64": "سيتم اظهار بياناتك في دليل التاجر",
          "65":
              "يمكنك تحديد ما تريد اعلانه من بياناتك الشخصية لغرض عرضها في دليل التاجر",
          "66": "الرجاء تشغيل الموقع",
          "67": "اعادة تعيين كلمة المرور",
          "68": "كلمة المرور الجديدة",
          "69": "اعادة كتابة كلمة المرور",
          "70": "تغيير كلمة السر",
          "71": "الفيس بوك",
          "72": "رقم الهاتف",
          "73": "البريد الألكتروني",
          "74": "الموقع الرسمي",
          "75": "اخفاء الكل",
          "76": "سيتم اخفاء جميع بياناتك في دليل التاجر",
          "77": "لا",
          "78": "نعم",
          "79": "هل انت متآكد",
          "80": "اظهار الكل",
          "81": "كلمة المرور ضعيفة",
          "82": "يرجى كتابة كلمة المرور",
          "83": "كلمة السر غير متطابقة",
          "84": "تم تغيير كلمة المرور بنجاح",
          "85": "لا توجد بيانات",
          "86": "رقم الكتاب",
          "87": "تاريخ الكتاب",
          "88": "رقم الشهادة",
          "89": "تاريخ الشهادة",
          "90": "الرجاء ادخال اسم المستخدم",
          "91": "يرجى ادخال رمز التأكيد",
          "92": "تأكيد كلمة السر",
          "93": "رمز التأكيد خطا",
          "94": "تم ارسال رمز التأكيد",
          "95": "تم تغيير كلمة المرور",
          "96": "انشاء حساب",
          "97": "رقم",
          "98": "حرف",
          "99": "تحقق",
          "100": "يتم التحقق من البيانات",
          "101": "الرجاء ادخال البيانات",
          "102": "البريد الألكتروني",
          "103": "انشاء حساب",
          "104": "التوقيع",
          "105": "حسنا",
          "106": "لا توجد بيانات",
          "107": "ادخل الوصف",
          "108": "نبذة عن الشركة",
          "109": "رمز التأكيد",
          "110": "تحقق من رمز التأكيد",
          "111": "تسجيل الدخول",
          "112": "الغاء",
          "113": "يتم التحقق من البيانات\nيرجى الأنتظار",
          "114": "ادخل رقم الصنف الموجود في هوية غرفة تجارة بغداد",
          "115": "التقط الصورة الشخصية",
          "116": "التالي",
          "117": "صورة هوية تجارة بغداد امامية",
          "118": "صورة هوية تجارة بغداد خلفية",
          "119": "يرجى ادراج جميع الصور المطلوبة",
          "120": "رجوع",
          "121": "ارسال طلب",
          "122": "اتعهد ان جميع البيانات صحيحة",
          "123": "يرجى ملأ جميع الحقول الموجودة",
          "124": "تم ارسال الطلب  بنجاح\nسيتم الرد خلال 48 ساعة",
          "125": "الأسم الأول",
          "126": "اسم الاب",
          "127": "اسم الجد",
          "128": "اسم الأم",
          "129": "الجنس",
          "130": "تاريخ الولادة",
          "131": "المحافظة",
          "132": "مكتب المعلومات",
          "133": "محلة",
          "134": "زقاق",
          "135": "رقم المحل او المكتب او الشركة",
          "136": "ذكر",
          "137": "انثى",
          "138": "نوع بطاقة التعريف",
          "139": "تفاصيل العمل",
          "140": "المعلومات الشخصية",
          "141": "المنطقة",
          "142": "اقرب نقطة دالة",
          "143": "رقم المحل او العمارة",
          "144": "عقد الايجار",
          "145": "صورة البطاقة الوطنية امامية",
          "146": "صورة البطاقة الوطنية خلفية",
          "147": "صورة بطاقة السكن امامية",
          "148": "صورة بطاقة السكن خلفية",
          "149": "تاريخ اصدار البطاقة",
          "150": "رقم بطاقة التعريف",
          "151": "جهة الاصدار",
          "152": "معلومات هوية التجارة",
          "153": "اختر الصنف",
          "154": "تاريخ صلاحية هوية",
          "155": "رسوم الهوية",
          "156": "البطاقة الوطنية",
          "157": "هوية الاحوال",
          "158": "الصنف ممتاز",
          "159": "الصنف اول",
          "160": "الصنف ثاني",
          "161": "الصنف ثالث",
          "162": "الصنف رابع",
          "163": "يرجى التاكد من البريد الالكتروني",
          "164": "يرجى الانتظار",
          "165": "هوية جديدة",
          "166": "تجديد الهوية",
          "167": "بورصة العراق",
          "168": "تاريخ نفاذ البطاقة",
          "170": "يرجى ملأ بيانات البطاقة",
          "171": "اختر طريقة الدفع",
          "172": "رقم الدار",
          "173": "الدفع",
          "174": "حصلت مشكلة في عملية الدفع\nيرجى تكرار المحاولة لاحقا",
          "175": "تمت عملية الدفع بنجاح",
          "176": "سيتم استقطاع مبلغ",
          "177": "من المحفظة",
          "178": "اختر",
          "188": "لا توجد خدمة",
          "189": "غير ذلك",
          "190": "مكتب",
          "191": "محل",
          "192": "صيدلية",
          "193": "شركة",
          "194": "افران",
          "195": "تحميل صورة خلفية بيضاء",
          "196": "شركة",
          "197": "فرد",
          "198": "الكيان",
          "199": "اربيل",
          "200": "الأنبار",
          "201": "بابل",
          "202": "بغداد",
          "203": "البصرة",
          "204": "حلبجة",
          "205": "دهوك",
          "206": "القادسية",
          "207": "دبالى",
          "208": "ذي قار",
          "209": "السليمانية",
          "210": "صلاح الدين",
          "211": "كركوك",
          "212": "كربلاء",
          "213": "المثنى",
          "214": "ميسان",
          "215": "النجف",
          "216": "نينوى",
          "217": "واسط",
          "218": "المعلومات غير مطابقة",
          "219": "رقم الاجازة",
          "220": "تاريخ الاجازة",
          "221": "رقم الفاتورة",
          "222": "تاريخ الفاتورة",
          "223": "تحميل صورة الفاتورة مسحوبة سكنر",
          "224": "تحميل صورة الاجازة مسحوبة سكنر",
          "225": "عذرا..الحساب محجوز",
          "226": "رسوم شهادة المنشأ",
          "227": "الكتاب",
          "228": "شهادة المنشأ",
          "229":"جاري تدقيق المعاملة \n يرجى الانتظار لحين استكمال الاجراءات \n واعلامك برسالة على بريدك الالكتروني"
        },
        "en": {
          "1": "Username",
          "2": "Password",
          "3": "Forgot Your Password",
          "4": "Baghdad Chamber of Commerce",
          "5": "Chamber News",
          "6": "Trader's Guide",
          "7": "Conferences",
          "8": "Opposed",
          "9": "Services",
          "10": "Welcome",
          "11": "Merchant Data",
          "12": "Merchant ID",
          "13": "Merchant Certificate",
          "14": "Certificate Of Rigin",
          "15": "Issued Books",
          "16": "Setting",
          "17": "Trader's Guide",
          "18": "Profile Personly",
          "19": "Contact Us",
          "20": "Language",
          "21": "LogOut",
          "22": "Arabic",
          "23": "English",
          "24": "The Shop",
          "25": "Taxes",
          "26": "Customs",
          "27": "Error",
          "28": "Trader Entry",
          "29": "Entering The Government Agency",
          "30": "Skip",
          "31": "Have Account Already",
          "32": "Baghdad Chamber Of Commerce Confirms That To",
          "33": "Owner Of",
          "34": "Has Joined That Chamber on",
          "35": "As Amember Of The Grade",
          "36": "We Wish You Success In Serving The Iraqi Economy",
          "37": "Name",
          "38": "Trade Name",
          "39": "Activity",
          "40": "Grade",
          "41": "Grade No",
          "42": "Affiliation Date",
          "43": "Expire Date",
          "44": "Managing Director",
          "45": "Location",
          "46": "Address",
          "47": "Phone Number",
          "48": "Web Site",
          "49": "Save",
          "50": "Search",
          "51": "Please Select",
          "52": "Please check your internet connection",
          "53": "Please Ensure That The Information Is Correct",
          "54": "Income Tax",
          "55": "Corporate Tax",
          "56": "Vent",
          "57": "Import Invoices",
          "58": "Cryptocurrency Statements",
          "59": "Customs Fees",
          "60": "Electronic transactions",
          "61": "Request for Transaction",
          "62": "Track Transaction",
          "63": "Login",
          "64": "Your Data Will Be Shown In The Merchant Directory",
          "65":
              "You Can Specify What You Want To Announce From Your Personal Data For The Purpose Of Displaying It In The Merchant's Guide",
          "66": "Please Run Location",
          "67": "Password Reset",
          "68": "New Password",
          "69": "Retype password",
          "70": "Change Password",
          "71": "Facebook",
          "72": "Phone",
          "73": "Email",
          "74": "Website",
          "75": "Hide All",
          "76": "All Your Data Will Be Hidden In The Merchant Directory",
          "77": "No",
          "78": "Yes",
          "79": "Are You Sure",
          "80": "Show All",
          "81": "The Password Is Weak",
          "82": "Please Type In The Password",
          "83": "Password Does Not Match",
          "84": "Password Changed Successfully",
          "85": "There Is No Data",
          "86": "Book No",
          "87": "Book Date",
          "88": "Certificate No",
          "89": "Certificate Date",
          "90": "Please Enter Your Username",
          "91": "Please Enter The Confirmation Code",
          "92": "Password Confirmation",
          "93": "The Confirmation Code Is Wrong",
          "94": "The Verification Code Has Been Sent",
          "95": "Password Has Been Changed",
          "96": "Create Account",
          "97": "No",
          "98": "Letter",
          "99": "Check",
          "100": "The Data Is Being Verified",
          "101": "Please Enter Data",
          "102": "Email",
          "103": "Create Account",
          "104": "Signature",
          "105": "OK",
          "106": "There Is No Data",
          "107": "Enter Description",
          "108": "About The Company",
          "109": "Confirmation Code",
          "110": "Check Confirmation Code",
          "111": "Login",
          "112": "Cancel",
          "113": "Data Is Being Verified\nPlease Wait",
          "114": "Enter The Grade No In The Baghdad Chamber Of Commerce ID",
          "115": "Take The Photo",
          "116": "Next",
          "117": "Baghdad Trade Identity Front Photo",
          "118": "Baghdad Trade Identity Background Photo",
          "119": "Please Include All Required photos",
          "120": "Back",
          "121": "Send Request",
          "122": "I Undertake That All Data Are Correct",
          "123": "Please Fill In All Fields",
          "124":
              "The Request Has Been Sent Successfully\nYou Will Receive A Response Within 48 Hours",
          "125": "First Name",
          "126": "Father's Name",
          "127": "Grandfather Name",
          "128": "Mother's name",
          "129": "Gender",
          "130": "Date of Birth",
          "131": "The Governorate",
          "132": "Information Office",
          "133": "Locality",
          "134": "Alley",
          "135": "The Number Of The Shop, Office Or Company",
          "136": "Male",
          "137": "Female",
          "138": "ID Type",
          "139": "Details Of Work",
          "140": "Personal Information",
          "141": "Region",
          "142": "Nearest Function Point",
          "143": "Store Or Building Number",
          "144": "Rent Contract",
          "145": "Front Photo Of The National Card",
          "146": "Back Photo Of The National Card",
          "147": "Front Residence Card Photo",
          "148": "Back Residence Card Photo",
          "149": "The Date Of Issuance Of The Card",
          "150": "ID Card Number",
          "151": "Issuer",
          "152": "Trade Identification Information",
          "153": "Choose The Category",
          "154": "Identity Expiration Datse",
          "155": "Identity Price",
          "156": "National card",
          "157": "Identity of Conditions",
          "158": "The Class Is Excellent",
          "159": "First Class",
          "160": "Second Class",
          "161": "The Third Class",
          "162": "The Fourth Class",
          "163": "Please Check Your Email",
          "164": "Please wait",
          "165": "New Identity",
          "166": "Identity Renewal",
          "167": "Iraq Stock Exchange",
          "168": "The Effective Date Of The Card",
          "170": "Please Fill The Card Information",
          "171": "Choose the payment method",
          "172": "House No.",
          "173": "Payment",
          "174":
              "There Was A Problem With The Payment Process\nPlease Try Again Later",
          "175": "Payment Completed Successfully.",
          "176": "An Amount Will Be Deducted",
          "177": "From Wallet",
          "178": "Select",
          "188": "There Is No Service",
          "189": "Other Than That",
          "190": "Office",
          "191": "Place",
          "192": "Pharmacy",
          "193": "Company",
          "194": "Ovens",
          "195": "Upload A White Background Image",
          "196": "Company",
          "197": "Individuals",
          "198": "The Entity",
          "199": "Erbil",
          "200": "Anbar",
          "201": "Babel",
          "202": "Baghdad",
          "203": "Basra",
          "204": "Halabja",
          "205": "Dohuk",
          "206": " Al-Qadisiyah",
          "207": "Dabali",
          "208": "Dhi Qar",
          "209": "Sulaymaniyah",
          "210": "Saladin",
          "211": "Kirkuk",
          "212": "Karbala",
          "213": "Al-Muthanna",
          "214": "Maysan",
          "215": "Najaf",
          "216": "Nineveh",
          "217": "Wasit",
          "218": "The Information Does Not Match",
          "219": "Vacation No.",
          "220": "Vacation Date",
          "221": "Invoice No.",
          "222": "Invoice Date",
          "223": "Upload a Scanner Photo Of The Invoice",
          "224": "Uploading a Scanner Photo Of The Vacation ",
          "225": "Sorry, The Account Is Reserved",
          "226": "Certificate of Origin Price",
          "227": "The Book",
          "228": "Certificate of Origin",
          "229": "The transaction is being audited\nPlease wait until the procedures are completed\nand you will be notified by an e-mail"

        }
      };
}
