name: books
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  http: ^1.2.0
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.4.0
  card_swiper: ^3.0.1
  bottom_bar_matu: ^1.3.1
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^24.1.47
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
