// ignore_for_file: file_names

import 'package:get/route_manager.dart';

class MyTransition extends Translations {
//  اللغات
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "المحفظة",
          "2": "التحويلات",
          "3": "الخدمات",
          "4": "الاعدادات",
          "5": "رصيدك الحالي",
          "6": "منصة العراق",
          "7": "من",
          "8": "الى",
          "9": "الوكلاء",
          "10": "اصدار بطاقة",
          "11": "العمليات الجارية",
          "12": "المعلومات الشخصية",
          "13": "تغيير كلمة المرور",
          "14": "اللغة",
          "15": "تسجيل خروج",
          "16": "تسجيل دخول",
          "17": "تحويل الرصيد",
          "18": "الاشعارات",
          "19": "اخر استقطاع",
          "20": "اخر تعبئة",
          "21": "العربية",
          "22": "الأنكليزية",
          "23": "مرحبا",
          "24": "البريد الألكتروني",
          "25": "كلمة المرور",
          "26": "نسيت كلمة المرور ؟",
          "27": "اسم المستخدم",
          "28": "رقم البطاقة",
          "29": "حفظ",
          "30": "كلمة المرور الجديدة",
          "31": "اعادة كتابة كلمة المرور",
          "32": "كلمة المرور ضعيفة",
          "33": "يرجى كتابة كلمة المرور",
          "34": "كلمة المرور غير متطابقة",
          "35": "تغيير كلمة المرور",
          "36": "مبلغ التحويل",
          "37": "رقم البطاقة",
          "38": "تحويل",
          "39": "كلمة المرور القديمة",
          "40": "اظهار معلومات البطاقة",
          "41": "عرض الرصيد",
          "42": "محفظتي",
          "43": "اضافة رصيد",
          "44": "رصيدك الحالي في المحفظة",
          "45": " ما هو المبلغ الذي تريد اضافته الى البطاقة",
          "46": "اخفاء معلومات البطاقة",
          "47": "اختر طريقة الامان",
          "48": "رقم بطاقة الشخص المستلم"
        },
        "en": {
          "1": "Credit Card",
          "2": "Transfers",
          "3": "Services",
          "4": "Setting",
          "5": "Your Current Balance",
          "6": "GCC IQ",
          "7": "From",
          "8": "To",
          "9": "Agents",
          "10": "Issuing A Card",
          "11": "Ongoing Operations",
          "12": "Personal Information",
          "13": "Change Password",
          "14": "Language",
          "15": "Log out",
          "16": "Log in",
          "17": "Convert Conversion",
          "18": "Notifcation",
          "19": "Last Deduction",
          "20": "Last Refill",
          "21": "Arabic",
          "22": "English",
          "23": "Welcome",
          "24": "Email",
          "25": "Password",
          "26": "Forget Your Password ?",
          "27": "Username",
          "28": "Card No.",
          "29": "Save",
          "30": "New Password",
          "31": "Retype password",
          "32": "The Password Is Weak",
          "33": "Please Type In The Password",
          "34": "Password Does Not Match",
          "35": "Change Password",
          "36": "Transfer Amount",
          "37": "Card No.",
          "38": "Transfer",
          "39": "Old Password",
          "40": "Show Card Information",
          "41": "View Balance",
          "42": "Wallet",
          "43": "Add Credit",
          "44": "Your Current Wallet Balance",
          "45": "What Is The Amount You Want To Add To The Card ?",
          "46": "Hide Card Information",
          "47": "Choose A Safe Method",
          "48": "The Recipient's Card No."
        }
      };
}
