name: templete
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sliding_clipped_nav_bar: ^3.1.0+4
  clipboard: ^0.1.3
  fluttertoast: ^8.2.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
