// ignore_for_file: file_names

import 'package:get/route_manager.dart';

class MyTransition extends Translations {
//  اللغات
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "منصة العراق الاقتصادية",
          "2": "المنتجات",
          "3": "الأقسام",
          "4": "الماركات",
          "5": "محفظتي",
          "6": "معلومات الحساب",
          "7": "اللغة",
          "8": "الأشعارات",
          "9": "تواصل معنا",
          "10": "الأعدادات",
          "11": "خدمة العملاء",
          "12": "مركز المساعدة",
          "13": "عن الشركة",
          "14": "الفاتورة",
          "15": "تسجيل الدخول",
          "16": "تسجيل الخروج",
          "17": "الأعدادات",
          "18": "حسابي",
          "19": "دليل الشركات",
          "20": "ابحث عن ...",
          "21": "أسم الشركة",
          "22": "النشاط",
          "23": "الفلترة",
          "24": "تنبيه",
          "25": "يرجى التحقق من اتصال الأنترنت",
          "26": "حسناً",
          "27": "العربية",
          "28": "الأنكليزية",
          "29": "اضافة رصيد",
          "30": "رصيدك الحالي",
          "31": "عرض الحركات المالية",
          "32": "من",
          "33": "الى",
          "34": "تحويل الرصيد",
          "35": "أسم المستخدم",
          "36": "البريد الألكتروني",
          "37": "كلمة المرور",
          "38": "رقم الهاتف",
          "39": "حفظ",
          "40": "من الحساب",
          "41": "رقم الحساب",
          "42": "تحويل",
          "43": "مبلغ التحويل",
          "44": "العنوان",
          "45": "كشف حساب",
          "46": "اختر طريقة الدفع",
          "47": "أدفع",
          "48": "حسناً",
          "49": "تمت العملية بنجاح",
          "50": "الأقسام",
          "51": "عرض الكل",
          "52": "اضاف حديثاً",
          "53": "الاكثر مبيعاً",
          "54": "جديد",
          "55": "اهلا بك",
          "57": "أنشاء حساب",
          "58": "نسيت كلمة المرور",
          "59": "تسجيل الدخول",
          "60": "لديك حساب بالفعل",
          "61": "أنشاء حساب",
          "62": "يرجى ادخال البريد الألكتروني",
          "63": "ارسال الرمز",
          "64": "عن طريق البريد الألكتروني",
          "65": "عن طريق رسالة واتساب",
          "66": "أختر طريقة الوصول",
          "67": "يرجى ادخال الرمز",
          "68": "ادخل الرمز",
          "69": "أدخل كلمة المرور الجديدة",
          "70": "تأكيد كلمة المرور الجديدة",
          "71": "تغيير كلمة المرور",
          "72": "يرجى ادخال كلمة المرور الجديدة",
          "73": "المفضلات",
          "74": "تم انشاء الحساب بنجاح",
          "75": "حسناً",
          "76": "يرجى التأكد من البريد الألكتروني",
          "77": "يرجى ادخال جميع البيانات المطلوبة"
        },
        "en": {
          "1": "Gcc.IQ",
          "2": "Product",
          "3": "Sections",
          "4": "Brands",
          "5": "My Wallet",
          "6": "Account Information",
          "7": "Language",
          "8": "Notifications",
          "9": "Contact us",
          "10": "Setting",
          "11": "Customer Service",
          "12": "Help Center",
          "13": "About the Company",
          "14": "Invoice",
          "15": "Login",
          "16": "Sign Out",
          "17": "Setting",
          "18": "My Account",
          "19": "Companies Guide",
          "20": "Search About ...",
          "21": "Company Name",
          "22": "Activity",
          "23": "Filter",
          "24": "Warning",
          "25": "Please check your internet connection",
          "26": "Okay",
          "27": "Arabic",
          "28": "English",
          "29": "Add credit",
          "30": "Your Current Balance",
          "31": "Presentation of Financial Transactions",
          "32": "From",
          "33": "To",
          "34": "Balance Transfer",
          "35": "Username",
          "36": "Email",
          "37": "Password",
          "38": "Phone number",
          "39": "Save",
          "40": "From The Account",
          "41": "Account Number",
          "42": "Transformation",
          "43": "Transfer Amount",
          "44": "Address",
          "45": "Statement Of Account",
          "46": "Choose The Method Of Payment",
          "47": "Pay",
          "48": "OK",
          "49": "The Operation Was Completed Successfully",
          "50": "Section",
          "51": "Show All",
          "52": "New Item",
          "53": "Best Seller",
          "54": "New",
          "55": "Welcome",
          "57": "Create Account",
          "58": "Forget Your Passowrd",
          "59": "Log In",
          "60": "You already have an account",
          "61": "Create Account",
          "62": "Please Enter Your Email Address",
          "63": "Send Code",
          "64": "By E-mail",
          "65": "By WhatsApp Message",
          "66": "Choose The method Of Access",
          "67": "Please Enter The Code",
          "68": "Enter The Code",
          "69": "Enter The New Password",
          "70": "Confirm New Password",
          "71": "Change Password",
          "72": "Please Enter A New Password",
          "73": "Favourite",
          "74": "The Account Was Created Successfully",
          "75": "Ok",
          "76": "Please Check Your Email",
          "77": "Please Enter All Required Information"
        }
      };
}
